### PR TITLE
don't fail when HAFAS returns an Exception

### PR DESCRIPTION
**Pull request by evgeni**
When there are no journeys found, pyHAFAS throws an exception.
Let's catch it, instead of spamming the logs :)

```
2024-10-04 10:16:40.247 ERROR (MainThread) [homeassistant.components.sensor] hafas: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 724, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/hafas/sensor.py", line 107, in async_update
    self.journeys = await self.hass.async_add_executor_job(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/pyhafas/client.py", line 157, in journeys
    res = self.profile.request(body)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/pyhafas/profile/base/helper/request.py", line 96, in request
    return HafasResponse(res, BaseErrorCodesMapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.12/site-packages/pyhafas/types/hafas_response.py", line 30, in __init__
    self.check_for_errors(mapping)
  File "/config/deps/lib/python3.12/site-packages/pyhafas/types/hafas_response.py", line 53, in check_for_errors
    raise mapping[self.data['svcResL'][0]['err']].value(
pyhafas.types.exceptions.JourneysArrivalDepartureTooNearError: HAFAS Kernel: No connection found
```

I've chosen to catch *all* exceptions, as pyhafas Exceptions don't have
any base class (besides Exception) and I thought it's nicer to report no
journeys for any error case.

### CODE REVIEW

**Comment by akloeckner** [comment]
Thanks! That's a good idea. Should we still issue a one-line warning? If we simply fail silently, the user might think, there simply are no connections...

**Comment by evgeni** [comment]
You mean in the log? We certainly could.

The current code makes the UI render the state as "Unknown", which for me is sufficient, but not all users are me ;)

Any preferred wording? Or just a:
```python
except Exception as e:
    _LOGGER.warning(f"Couldn't fetch journeys: {e}")
```

**Comment by akloeckner** [comment]
Yes, I meant in the log. I think `unknown` is the correct state, if there are no trips.

I suggest to also include the entity ID in the message, since that's where the user could check the configuration. Such that something like this results: 

`
2024-10-04 10:16:40.247 WARNING (MainThread) [homeassistant.components.sensor.hafas] Couldn't fetch journeys for sensor.a_to_b: pyhafas.types.exceptions.JourneysArrivalDepartureTooNearError
`

Would that make sense?

**Comment by evgeni** [comment]
that'd be `self.entity_id`, right? (first time touching HA internals)

**Comment by akloeckner** [comment]
I think so, yes. `self.entity_id` seems to be provided by the `Entity` base class.

**Review by akloeckner — APPROVED** [review]
Thanks! This seems to work great here, too. It looks much tidier in the logs.

**Comment by akloeckner** [comment]
I just realized, yours is the first community contribution here. 🎉 

Thanks again. I just created a new release with the change.

**Pull request merged**
